### ISSUE TITLE
设置网页的默认全局字体

### ISSUE THREAD

**Issue by xihaoshangdi** [xihaoshangdi/xihaoshangdi.blog#22]
```css

@font-face {
  font-family: Emoji;
  src: local("Apple Color Emojiji"), local("Segoe UI Emoji"), local("Segoe UI Symbol"), local("Noto Color Emoji");
  unicode-range: U+1F000-1F644, U+203C-3299;
}
body {
  font-family: system-ui, —apple-system, Segoe UI, Rototo, Emoji, Helvetica, Arial, sans-serif;
}
//衬线字体：
.font-serif {
  font-family: Georgia, Cambria, "Times New Roman", Times, serif;
}
//等宽字体：
.font-mono {
  font-family: Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
```
